- platform: mqtt
  name: megaio-relay-1
  icon: mdi:electric-switch
  state_topic: "megaio/switch/relay-1/state"
  command_topic: "megaio/switch/relay-1/set"
- platform: mqtt
  name: megaio-relay-2
  icon: mdi:electric-switch
  state_topic: "megaio/switch/relay-2/state"
  command_topic: "megaio/switch/relay-2/set"
- platform: mqtt
  name: megaio-relay-3
  icon: mdi:electric-switch
  state_topic: "megaio/switch/relay-3/state"
  command_topic: "megaio/switch/relay-3/set"
- platform: mqtt
  name: megaio-relay-4
  icon: mdi:electric-switch
  state_topic: "megaio/switch/relay-4/state"
  command_topic: "megaio/switch/relay-4/set"
- platform: mqtt
  name: megaio-relay-5
  icon: mdi:electric-switch
  state_topic: "megaio/switch/relay-5/state"
  command_topic: "megaio/switch/relay-5/set"
- platform: mqtt
  name: megaio-relay-6
  icon: mdi:electric-switch
  state_topic: "megaio/switch/relay-6/state"
  command_topic: "megaio/switch/relay-6/set"
- platform: mqtt
  name: megaio-relay-7
  icon: mdi:electric-switch
  state_topic: "megaio/switch/relay-7/state"
  command_topic: "megaio/switch/relay-7/set"
- platform: mqtt
  name: megaio-relay-8
  icon: mdi:electric-switch
  state_topic: "megaio/switch/relay-8/state"
  command_topic: "megaio/switch/relay-8/set"

