- platform: command_line
  scan_interval: 5
  switches:
    pihole:
      friendly_name: "Ad Blocking"
      command_on: "/config/scripts/pihole.py --enable"
      command_off: "/config/scripts/pihole.py --disable"
      command_state: "/config/scripts/pihole.py --status"
      value_template: "{{ value_json.status == 'enabled' }}"
