
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include_dir_merge_named groups
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include_dir_merge_list sensors
switch: !include_dir_merge_list switches

zwave:
    usb_path: /dev/serial/by-id/usb-0658_0200-if00
    network_key: "0x6A, 0x7F, 0x13, 0x1F, 0x5E, 0x4F, 0x2A, 0xCE, 0xFF, 0x49, 0xD0, 0xD3, 0xF5, 0xF9, 0xAF, 0x9A"
    device_config: !include zwave_device_config.yaml

mqtt_statestream:
  base_topic: homeassistant
  publish_attributes: true
  publish_timestamps: true

homekit:
  auto_start: false
  filter:
    include_domains:
      - light
    include_entities:
      - sensor.garage_sensor_temperature
      - sensor.kids_bedroom_sensor_temperature
      - switch.kitchen_countertop_light
      - switch.shed_inside_light
      - switch.pihole
      - switch.megaio_relay_1
  entity_config:
    light.guest_bathroom_mirror_light:
      # light.honeywell_39351_zw3005_in_wall_smart_dimmer_level
      name: Mirror Light
    light.guest_bathroom_ceiling_light:
      # light.honeywell_39351_zw3005_in_wall_smart_dimmer_level_2
      name: Ceiling Light
    light.kitchen_ceiling_light:
      # light.honeywell_39351_zw3005_in_wall_smart_dimmer_level_3
      name: Ceiling Light
    light.dining_room_light:
      # light.honeywell_39351_zw3005_in_wall_smart_dimmer_level_4
      name: Dining light
    switch.kitchen_countertop_light:
      # switch.honeywell_unknown_type_4952_id_3036_switch
      name: Countertop Light
    switch.shed_inside_light:
      # switch.honeywell_unknown_type_4952_id_3036_switch_2
      name: Shed Inside Light
    light.shed_outside_light:
      # light.honeywell_39351_zw3005_in_wall_smart_dimmer_level_5
      name: Shed Outside_light
    switch.pihole:
      name: Ad Blocker
    switch.megaio_relay_1:
      name: Relay 1

homeassistant:
  customize: !include customize.yaml
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: America/Los_Angeles
  name: Home
  whitelist_external_dirs:
    - /tmp

#mqtt:
#  broker: core-mosquitto.local.hass.io
#  discovery: true
#  discovery_prefix: megaio

recorder:
  db_url: mysql://hass:CR6aFsYsBzd8?utZdVT*W8WR@core-mariadb/homeassistant?charset=utf8
  purge_keep_days: 999

pi_hole:
  - host: !secret pihole_api_host
    api_key: !secret pihole_api_token

